# -*- coding: utf-8 -*-
"""
/***************************************************************************
 proyecto_posg
                                 A QGIS plugin
 Analisis espacial para la localizacion de infraestructura escolar
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-15
        copyright            : (C) 2026 by Dayron Caicedo
        email                : dayronlalay8@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load proyecto_posg class from file proyecto_posg.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .proyecto_posg import proyecto_posg
    return proyecto_posg(iface)
