# -*- coding: utf-8 -*-
"""
/***************************************************************************
 proyecto_posgDockWidget
                                 A QGIS plugin
 Analisis espacial para la localizacion de infraestructura escolar
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-15
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Dayron Caicedo
        email                : dayronlalay8@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import processing

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal
from qgis.core import QgsProject, QgsVectorFileWriter, QgsVectorLayer, QgsField, QgsFeature, QgsGeometry
from PyQt5.QtCore import QVariant
from qgis.gui import QgsFileWidget
from qgis.PyQt.QtWidgets import QMessageBox

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'proyecto_posg_dockwidget_base.ui'))


class proyecto_posgDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(proyecto_posgDockWidget, self).__init__(parent)
        self.setupUi(self)
        self.btn_cargar.clicked.connect(self.cargar)
        self.btn_ejecutar.clicked.connect(self.ejecutar)
        self.btn_exportar.clicked.connect(self.exportar)
        self.cmb_area_min.currentIndexChanged.connect(self.seleccionar)
        self.cmb_formatos.currentIndexChanged.connect(self.seleccionar)
    
    def cargar(self):
        """Valida que todas las coberturas necesarias estén cargadas correctamente."""
        project = QgsProject.instance()
        layers_dict = {layer.name(): layer for layer in project.mapLayers().values()}
        
        # Configuración de capas requeridas
        required_layers = {
            "MANZANAS": {
                "required_fields": ["ID_MANZANA", "AREA"],
                "crs": 3116
            },
            "USO_SUELO": {
                "required_fields": ["TIPO_USO", "AREA"],
                "crs": 3116
            },
            "ESCUELAS": {
                "required_fields": ["NOMBRE", "CATEGORIA"],
                "crs": 3116
            },
            "EQUIPAMIENTOS_A": {
                "required_fields": ["NOMBRE"],
                "crs": 3116
            },
            "EQUIPAMIENTOS_B": {
                "required_fields": ["NOMBRE"],
                "crs": 3116
            }
        }
        
        errors = []
        
        # Validar cada capa
        for layer_name, config in required_layers.items():
            if layer_name not in layers_dict:
                errors.append(f"❌ La capa '{layer_name}' no está cargada en el proyecto.")
                continue
            
            layer = layers_dict[layer_name]
            
            # 1. Validar CRS (debe ser exactamente 3116)
            crs_auth = layer.crs().authid()  # Ejemplo: "EPSG:3116"
            if "3116" not in crs_auth:
                errors.append(f"❌ {layer_name} → CRS incorrecto: {crs_auth} (se requiere EPSG:3116)")
            
            # 2. Validar campos requeridos (nombres exactos)
            layer_fields = [field.name() for field in layer.fields()]
            missing_fields = []
            
            for field in config["required_fields"]:
                if field not in layer_fields:
                    missing_fields.append(field)
            
            if missing_fields:
                errors.append(f"❌ {layer_name} → Faltan los campos: {', '.join(missing_fields)}")
        
        # Mensajes de validación
        if errors:
            # Falló la validación
            self.txt_cargadas.setText("VALIDACION INCORRECTA")
            self.txt_cargadas.setStyleSheet("color: red; font-weight: bold;")
            # Mensaje de rechazo
            mensaje_error = "No se puede continuar con el análisis.\n\n"
            mensaje_error += "Se detectaron los siguientes problemas:\n\n"
            mensaje_error += "\n".join(errors)
            
            QMessageBox.critical(self, "Error de Validación", mensaje_error)
            return False
        
        else:
            # Validación exitosa
            self.txt_cargadas.setText("OK")
            self.txt_cargadas.setStyleSheet("color: green; font-weight: bold;")
            # Mensaje de éxito
            success_msg = "✅ Validación exitosa\n\n"
            success_msg += "Todas las coberturas están aptas para el análisis:\n\n"
            for layer_name in required_layers.keys():
                success_msg += f"• {layer_name} ✓\n"
            
            QMessageBox.information(self, "Validación Exitosa", success_msg)

            self.cmb_area_min.clear()
            lista_areas = ["2500","3000","5000"]
            self.cmb_area_min.addItems(lista_areas)

            lista_formatos = [".shp", ".kml", ".gpkg", ".gjson"]
            self.cmb_formatos.addItems(lista_formatos)

            return True

    def seleccionar(self):
        self.txt_area_min.setText(self.cmb_area_min.currentText())

    def ejecutar(self):
        try:


            # Capas del proyecto
            manzanas = QgsProject.instance().mapLayersByName("MANZANAS")[0]
            uso_suelo = QgsProject.instance().mapLayersByName("USO_SUELO")[0]
            escuelas = QgsProject.instance().mapLayersByName("ESCUELAS")[0]
            equip_a = QgsProject.instance().mapLayersByName("EQUIPAMIENTOS_A")[0]
            equip_b = QgsProject.instance().mapLayersByName("EQUIPAMIENTOS_B")[0]

            # Selección de area minima
            area_min = float(self.cmb_area_min.currentText())

            # seleccionar escuelas primarias
            escuelas_primarias = processing.run(
                "native:extractbyexpression",
                {
                    'INPUT': escuelas,
                    'EXPRESSION': "upper(trim(\"CATEGORIA\")) = 'PRIMARIA'",
                    'OUTPUT': 'memory:'
                },
            )['OUTPUT']

            # generar buffer de escuelas
            buffer_escuelas = processing.run(
                "native:buffer",
                {
                    'INPUT': escuelas_primarias,
                    'DISTANCE': 300,
                    'DISSOLVE': True,
                    'OUTPUT': 'memory:'
                },
            )['OUTPUT']

            # join de equipamentos
            equipamientos = processing.run(
                "native:mergevectorlayers",
                {
                    'LAYERS': [equip_a, equip_b],
                    'CRS': manzanas.crs(),
                    'OUTPUT': 'memory:'
                },
            )['OUTPUT']

            # generar buffer de equipamentos
            buffer_equipamientos = processing.run(
                "native:buffer",
                {
                    'INPUT': equipamientos,
                    'DISTANCE': 200,
                    'DISSOLVE': True,
                    'OUTPUT': 'memory:'
                },
            )['OUTPUT']

            # extraer uso residencial
            uso_residencial = processing.run(
                "native:extractbyexpression",
                {
                    'INPUT': uso_suelo,
                    'EXPRESSION': "upper(trim(\"TIPO_USO\")) = 'RESIDENCIAL'",
                    'OUTPUT': 'memory:'
                },
            )['OUTPUT']

            # manzana de area minima
            manzanas_area = processing.run(
                "native:extractbyexpression",
                {
                    'INPUT': manzanas,
                    'EXPRESSION': f"\"AREA\" >= {area_min}",
                    'OUTPUT': 'memory:'
                },
            )['OUTPUT']

            # fuera del buffer escuelas
            fuera_escuelas = processing.run(
                "native:extractbylocation",
                {
                    'INPUT': manzanas_area,
                    'PREDICATE': [2],  
                    'INTERSECT': buffer_escuelas,
                    'OUTPUT': 'memory:'
                },
            )['OUTPUT']

            # fuera del buffer equipamentos
            fuera_equipamientos = processing.run(
                "native:extractbylocation",
                {
                    'INPUT': fuera_escuelas,
                    'PREDICATE': [2],  
                    'INTERSECT': buffer_equipamientos,
                    'OUTPUT': 'memory:'
                },
            )['OUTPUT']

            # contenido en zonas residenciales
            resultado = processing.run(
                "native:extractbylocation",
                {
                    'INPUT': fuera_equipamientos,
                    'PREDICATE': [6],  
                    'INTERSECT': uso_residencial,
                    'OUTPUT': 'memory:'
                },
            )['OUTPUT']

            # resultados con informacion 
            features = list(resultado.getFeatures())

            if len(features) == 0:

                QMessageBox.warning(
                    self,
                    "Sin resultados",
                    "No existen manzanas que cumplan los criterios establecidos."
                )

                return

            # Manzana de area menor como resultado final
            menor = min(features, key=lambda f: f['AREA'])

            resultado_final = processing.run(
                "native:extractbyexpression",
                {
                    'INPUT': resultado,
                    'EXPRESSION': f'"AREA" = {menor["AREA"]}',
                    'OUTPUT': 'memory:'
                }
            )['OUTPUT']

            self.resultado_final = resultado_final

            QgsProject.instance().addMapLayer(resultado_final)

            # Datos en la tabla
            self.twg_datos_mzn.setRowCount(0)
            for feature in resultado_final.getFeatures():
                fila = self.twg_datos_mzn.rowCount()
                self.twg_datos_mzn.insertRow(fila)
                self.twg_datos_mzn.setItem(
                    fila,
                    0,
                    QtWidgets.QTableWidgetItem(str(feature['ID_MANZANA']))
                )
                self.twg_datos_mzn.setItem(
                    fila,
                    1,
                    QtWidgets.QTableWidgetItem(str(feature['AREA']))
                )

            QMessageBox.information(
                self,
                "Proceso completado",
                "El análisis espacial finalizó correctamente."
            )


        except Exception as e:

            QMessageBox.critical(
                self,
                "Error",
                str(e)
            )


    def exportar(self):
        try:

            if not hasattr(self, 'resultado_final'):
                QMessageBox.warning(
                    self,
                    "Advertencia",
                    "Primero debe ejecutar el análisis."
                )
                return

            # filtrado por formato
            formato = self.cmb_formatos.currentText()

            if formato == ".shp":
                filtro = "Shapefile (*.shp)"
                driver = "ESRI Shapefile"

            elif formato == ".kml":
                filtro = "KML (*.kml)"
                driver = "KML"

            elif formato == ".gpkg":
                filtro = "GeoPackage (*.gpkg)"
                driver = "GPKG"

            elif formato == ".gjson":
                filtro = "GeoJSON (*.geojson)"
                driver = "GeoJSON"

            else:
                QMessageBox.warning(
                    self,
                    "Error",
                    "Formato no válido."
                )
                return

            # ventana para obtener ruta de guardar
            ruta_salida, _ = QtWidgets.QFileDialog.getSaveFileName(
                self,
                "Guardar resultado",
                "",
                filtro
            )

            # Exportar
            error = QgsVectorFileWriter.writeAsVectorFormat(
                self.resultado_final,
                ruta_salida,
                "UTF-8",
                self.resultado_final.crs(),
                driver
            )

            # Validar exportación
            if error[0] == QgsVectorFileWriter.NoError:
                QMessageBox.information(
                    self,
                    "Éxito",
                    "La capa fue exportada correctamente."
                )

            else:
                QMessageBox.critical(
                    self,
                    "Error",
                    "No fue posible exportar la capa."
                )

        except Exception as e:
            QMessageBox.critical(
                self,
                "Error",
                str(e)
            )

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
